import { SignedIn, SignedOut, UserButton, useAuth } from "@clerk/nextjs";
import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";

import { api } from "~/utils/api";

const Home: NextPage = () => {
  const { userId, isLoaded, sessionId, isSignedIn } = useAuth();
  const hello = api.example.hello.useQuery({ text: "from tRPC" });

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center bg-gradient-to-b from-[#2e026d] to-[#15162c]">
        <SignedIn>
          <div className="flex flex-col items-center justify-center">
            <UserButton />

            <h1 className="text-4xl font-bold text-white">
              Welcome to T3 App!
            </h1>
            <p className="text-2xl text-white">You are signed in.</p>
            <p className="text-2xl text-white">Your user ID is: {userId}</p>
            <p className="text-2xl text-white">
              Your session ID is: {sessionId}
            </p>
          </div>
        </SignedIn>
        <SignedOut>
          <div className="flex flex-col items-center justify-center">
            <h1 className="text-4xl font-bold text-white">
              Welcome to T3 App!
            </h1>

            <p className="text-2xl text-white">You are signed out.</p>
            <p className="text-2xl text-white">
              <Link href="/auth/SignIn">
              Sign in
              </Link>
            </p>
          </div>
        </SignedOut>
      </main>
    </>
  );
};

export default Home;
