import {
    SignedIn,
    SignedOut,
    UserButton,
    useAuth,
    useUser,
} from '@clerk/nextjs';
import { type NextPage } from 'next';
import Head from 'next/head';
import Link from 'next/link';

import ChatScreen from './ChatScreen';

const Home: NextPage = () => {
    return (
        <>
            <Head>
                <title>Create T3 App</title>
                <meta name="description" content="Generated by create-t3-app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <NavBar />
            <main className="w-screen">
                <SignedIn>
                    <ChatScreen />
                </SignedIn>
                <SignedOut>
                    <div className="flex flex-col items-center justify-center">
                        <h1 className="text-4xl font-bold text-white">
                            Welcome to T3 App!
                        </h1>

                        <p className="text-2xl text-white">
                            You are signed out.
                        </p>
                        <p className="text-2xl text-white">
                            <Link href="/auth/SignIn">Sign in</Link>
                        </p>
                    </div>
                </SignedOut>
            </main>
        </>
    );
};

const NavBar: NextPage = () => {
    const { isSignedIn } = useAuth();
    const { user } = useUser();
    return (
        <nav className="flex justify-between p-4">
            <div className="w-52"></div>
            {/* TODO: add new font */}
            <h1 className="text-4xl">Chatter</h1>
            <div className="flex items-center gap-2">
                {isSignedIn && (
                    <div className="flex items-center gap-2">
                        <h5>
                            Willkommen{' '}
                            <span className="font-bold text-purple-500">
                                {user?.fullName}
                            </span>
                        </h5>
                        <UserButton />
                    </div>
                )}
            </div>
        </nav>
    );
};
export default Home;
